### ISSUE TITLE
Field Data Isn't Saving

### ISSUE THREAD

**Issue by theskyfloor** [quebecstudio/usergroupfield#1]
Hi! Testing out your plug-in but I can't get the field data to save to the entry in the latest version of Craft. Let me know if you are able to reproduce or if you would like more info.

**Comment by rtrudel** [comment]
Can you provide more information? It works as expected on the project I built it for.

**Comment by theskyfloor** [comment]
Hmm. Yeah:

Craft CMS 2.6.2968
Usergroup Field 1.0.0

Thats really all I have to offer. I assign the field to a section and select a group but when I save my entry it refreshes and no groups are selected.

**Comment by theskyfloor** [comment]
Forgive me if I am mistaken (not much of a plug-in developer) but is the function in the model folder correct? It seems to maybe have placeholder content. Perhaps the version on the working Craft install is different than the one in the repo? Once again forgive me of my ignorance I don't mean to make it sound like I know anything. This plug-in is great and so I am really excited to use it.

**Comment by dallimor** [comment]
I'm seeing the same issue here.

**Comment by rtrudel** [comment]
@theskyfloor seems you're right, I just installed on another site and I could reproduce... . I'm trying to find the difference and I'll push an update ASAP. Sorry for the inconvenience. Thanks for the good words about the plugin!

**Comment by rtrudel** [comment]
@theskyfloor @dallimor Can you please update and try again and confirm the fix? Thank you for your help!

Note: The field type is not labeled as "Group" anymore but "Usergroup" instead.

**Comment by theskyfloor** [comment]
Awesome change on the naming. The changes worked! Field now saves. Thanks for your help and this needed plug-in.
